//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EliteDangerous.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EliteDangerous.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aemonz EQ-Y e1899,,4549.97,-850.56,33732.38
        ///Aemonz WP-X e1-230,,3852.91,-321.16,33901.03
        ///Aemonz WZ-Y e2137,,3857.34,-576.5,33733.88
        ///Aemonz YK-P e5-68,,3865.31,-1287.53,34537.06
        ///Aemorrs CG-O e6-2183,,2312.81,-816.81,34644.41
        ///Aemorrs FB-X e1-3356,,1805.81,-792.78,33828.25
        ///Aemorrs HX-T e3-4455,,1531.47,-409.75,34137.81
        ///Aemorrs HX-T e3-4517,,1470.34,-469.34,34159.25
        ///Aemorrs KW-W e1-4401,,2241.31,-840.41,33926.31
        ///Aemorrs LC-U e3-1611,,2378.97,-295.13,34195.56
        ///Aemorrs LH-V e2-6480,,2063.41,-811.56,34049 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Marx_Nebula_List_26_10_21 {
            get {
                return ResourceManager.GetString("Marx_Nebula_List_26_10_21", resourceCulture);
            }
        }
    }
}
